project:
  type: manuscript

manuscript:
  article: index.qmd
  meca-bundle: false

format:
  html:
    comments:
      hypothesis: true
    css: report.styles.scss
  docx: default
  jats: default

fontsize: "14px"
mainfont: "Times New Roman"

  # (other formats)
  # pdf: default

execute:
  freeze: true

